### ISSUE TITLE
Failed to retriever maven metadata

### ISSUE THREAD

**Issue by hoshinokiseki** [4gname/UltraMine#2]
When i try to install ultramine as quickstart in this project's wiki, an error occured. and here is full error log (with --stacktrace arg)
```
D:\UltraMine>java -jar bootstrap.jar --stacktrace
Bootstrap for UltraMine Core 1.7.10
Retrieving versions
Failed to retriever maven metadata from http://maven.ultramine.ru/org/ultramine/core/ultramine_core-1.7.10-server/maven-metadata.xml
org.ultramine.bootstrap.exceptions.ApplicationErrorException: Failed to retriever maven metadata from http://maven.ultramine.ru/org/ultramine/core/ultramine_core-1.7.10-server/maven-metadata.xml
        at org.ultramine.bootstrap.maven.MavenMetadata.<init>(MavenMetadata.java:26)
        at org.ultramine.bootstrap.maven.MavenMetadata.loadFromXML(MavenMetadata.java:46)
        at org.ultramine.bootstrap.maven.MavenMetadata.loadFromProject(MavenMetadata.java:51)
        at org.ultramine.bootstrap.maven.MavenMetadata.loadFromProject(MavenMetadata.java:56)
        at org.ultramine.bootstrap.UMCoreVersionsRetriever.<init>(UMCoreVersionsRetriever.java:16)
        at org.ultramine.bootstrap.task.DependencyResolver.load(DependencyResolver.java:65)
        at org.ultramine.bootstrap.Main.main(Main.java:101)
Caused by: java.net.UnknownHostException: maven.ultramine.ru
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at java.net.Socket.connect(Socket.java:556)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:647)
        at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:806)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:177)
        at org.ultramine.bootstrap.maven.MavenMetadata.<init>(MavenMetadata.java:22)
        ... 6 more
```

**Comment by aagrishankov** [comment]
I am not the author of Ultramine, it is just a fork

**Comment by hoshinokiseki** [comment]
well... thank you
